Add possibility to ignore args/kwargs in memoize decorator
grantjenks/python-diskcache pull request #216
Opened 2021-06-29 13:05 UTC by oldrichsmejkal

Example call:
   @cache.memoize(ignored_args = [0], ignored_kwargs = ['arg4'])

2021-06-29 14:46 UTC, grantjenks commented
What’s the use case? Please describe or share a compelling example.

2021-06-29 14:52 UTC, grantjenks commented
Here’s what a quick Google search turned up:

- https://stackoverflow.com/questions/30730983/make-lru-cache-ignore-some-of-the-function-arguments
- https://www.reddit.com/r/learnpython/comments/3v75g4/using_functoolslru_cache_only_on_some_arguments/

The first example is compelling to me as it’s a problem I’ve had before too.

2021-06-29 15:00 UTC, grantjenks requested changes

2021-06-30 12:44 UTC, oldrichsmejkal commented on diskcache/core.py
> +                return args_to_key(base, args, kwargs, typed, ignored_args, ignored_kwargs)
Should be ready now

2021-09-07 06:14 UTC, grantjenks commented
I tried tonight to find a clever way around the `ignore_arguments` parameter using closures. There are some tricks we can play with Python but they're awfully confusing and not nearly as simple as what's here.

This is just to remind myself to merge the PR.

2021-09-14 04:55 UTC, grantjenks commented
Superseded by #226

2021-09-14 04:55 UTC, closed without merging